name: Compile Comskip Windows Donator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSYS2
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: >-
          git
          base-devel
          mingw-w64-x86_64-toolchain
          mingw-w64-x86_64-ffmpeg6
          mingw-w64-x86_64-argtable3

    - name: Compile Comskip Donator
      run: |
        ./autogen.sh
        ./configure --enable-donator --enable-gui
        make

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: comskip-windows-donator
        path: "*.exe"
