name: Compile Comskip Windows Donator

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Cross-Compiler and Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64 git build-essential autoconf automake libtool pkg-config libargtable2-dev

    - name: Download and Build FFmpeg 4.4 for Windows
      run: |
        git clone --depth 1 -b n4.4.4 https://github.com
        cd FFmpeg
        ./configure \
          --cross-prefix=x86_64-w64-mingw32- \
          --enable-cross-compile \
          --target-os=mingw32 \
          --arch=x86_64 \
          --disable-shared \
          --enable-static \
          --disable-programs \
          --disable-doc
        make -j$(nproc)
        sudo make install

    - name: Compile Comskip Donator
      run: |
        ./autogen.sh
        ./configure --host=x86_64-w64-mingw32 --enable-donator --disable-gui PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
        make

    - name: Upload Binary Artifact
      uses: actions/upload-artifact@v4
      with:
        name: comskip-windows-donator
        path: "*.exe"
